/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dawrig_ndkexample_Store */

#ifndef _Included_com_example_dawrig_ndkexample_Store
#define _Included_com_example_dawrig_ndkexample_Store
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dawrig_ndkexample_Store
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_dawrig_ndkexample_Store_getCount
  (JNIEnv *, jobject);

/*
 * Class:     com_example_dawrig_ndkexample_Store
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_dawrig_ndkexample_Store_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_dawrig_ndkexample_Store
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_dawrig_ndkexample_Store_setString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_dawrig_ndkexample_Store
 * Method:    getInteger
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_dawrig_ndkexample_Store_getInteger
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_dawrig_ndkexample_Store
 * Method:    setInteger
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_dawrig_ndkexample_Store_setInteger
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_dawrig_ndkexample_Store
 * Method:    getColor
 * Signature: (Ljava/lang/String;)Lcom/example/dawrig/ndkexample/Color;
 */
JNIEXPORT jobject JNICALL Java_com_example_dawrig_ndkexample_Store_getColor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_dawrig_ndkexample_Store
 * Method:    setColor
 * Signature: (Ljava/lang/String;Lcom/example/dawrig/ndkexample/Color;)V
 */
JNIEXPORT void JNICALL Java_com_example_dawrig_ndkexample_Store_setColor
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
