/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rendering_wright_esengine_nativec_NativeLib */

#ifndef _Included_rendering_wright_esengine_nativec_NativeLib
#define _Included_rendering_wright_esengine_nativec_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rendering_wright_esengine_nativec_NativeLib
 * Method:    Init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rendering_wright_esengine_nativec_NativeLib_Init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     rendering_wright_esengine_nativec_NativeLib
 * Method:    Resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_rendering_wright_esengine_nativec_NativeLib_Resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     rendering_wright_esengine_nativec_NativeLib
 * Method:    Update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rendering_wright_esengine_nativec_NativeLib_Update
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
