/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rendering_wright_hellotriangle_GLESNativeLib */

#ifndef _Included_rendering_wright_hellotriangle_GLESNativeLib
#define _Included_rendering_wright_hellotriangle_GLESNativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rendering_wright_hellotriangle_GLESNativeLib
 * Method:    initGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rendering_wright_hellotriangle_GLESNativeLib_initGL
        (JNIEnv *, jobject, jstring FilePath);

/*
 * Class:     rendering_wright_hellotriangle_GLESNativeLib
 * Method:    resizeGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rendering_wright_hellotriangle_GLESNativeLib_resizeGL
        (JNIEnv *, jobject, jint width, jint height);

/*
 * Class:     rendering_wright_hellotriangle_GLESNativeLib
 * Method:    updateGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rendering_wright_hellotriangle_GLESNativeLib_updateGL
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
